# Site settings
baseurl = "https://ongthang.com/"
languageCode = "vi-vn"
title = "Ông Thắng Phan Rang"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Ông Thắng"
  description = "Phan Rang - Tháp Chàm"
  email = "ongthangphanrang@gmail.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "OT Phan Rang"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Cam kết"
    portfolio = "Sản phẩm"
    about = "Lược sử"
    team = "Con người"
    contact = "Liên hệ"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    # [[menu.postpend]]
    #   url = "http://gohugo.io"
    #   name = "External link"
    #   weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "chúng tôi nâng cao giá trị"
    subtitle = "Nông sản Phan Rang"
    buttonText = "Tìm hiểu"


  # Services section
  [params.services]
    enable = true
    title = "Cam kết"
    subtitle = "Chất lượng dịch vụ"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-check"
      title = "Chất lượng"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Vệ sinh"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-lock"
      title = "An toàn"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "Kể chuyện Ông Thắng Phan Rang"
    subtitle = "Lược sử hình thành"
    endpoint = "Hãy tham gia cùng chúng tôi!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "1993"
      title = "Lên đường"
      description = "ông Thắng (ba Ánh) đưa cả nhà vào Phan Rang, khai hoang bãi nổi giữa cửa biển sông Dinh"

    [[params.about.events]]
      img = "2.jpg"
      date = "199x"
      title = "An Agency is Born"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "3.jpg"
      date = "December 2012"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "4.jpg"
      date = "July 2014"
      title = "Phase Two Expansion"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


  # Team section
  [params.team]
    enable = false


  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      center = true
      # Optional client title specifying the involvement
      title = "Đối tác / bạn đồng hành tin cậy"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "xanh.jpg"
        link = "https://xanhshop.com/"

  # Contact section
  [params.contact]
    enable = true
    title = "Liên hệ"
    subtitle  = "__Email__: [ongthangphanrang@gmail.com](mailto:ongthangphanrang@gmail.com)\n\n__Điện thoại__: [+84 994285978](tel:+84994285978‬)‬"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Copyright 2018"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    # [[params.footer.quicklinks]]
    #   text = "Privacy Policy"
    #   link = "#"

    # [[params.footer.quicklinks]]
    #   text = "Terms of Use"
    #   link = "#"
