# Site settings
baseurl = "https://ongthang.com/"
# baseurl = "http://localhost:1313/"
languageCode = "vi-vn"
title = "Ông Thắng Phan Rang"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Ông Thắng"
  description = "Phan Rang - Tháp Chàm"
  email = "ongthangphanrang@gmail.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "OT Phan Rang"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Giá trị"
    portfolio = "Sản phẩm"
    about = "Lược sử"
    team = "Con người"
    contact = "Liên hệ"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    # [[menu.postpend]]
    #   url = "http://gohugo.io"
    #   name = "External link"
    #   weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "chúng tôi nâng cao giá trị"
    subtitle = "Nông sản Phan Rang"
    buttonText = "Tìm hiểu"


  # Services section
  [params.services]
    enable = true
    title = "Giá trị cốt lõi"
    # subtitle = "Chất lượng dịch vụ"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-check"
      title = "Lành và sạch"
      description = "Sử dụng nguồn nguyên liệu không hoá chất. Đồng hành cùng những vườn canh tác thuận tự nhiên. Thực hành và lan tỏa lối sống thân thiện với môi trường."
      # url = "#"

    [[params.services.row.list]]
      icon = "fa-heart"
      title = "Tử tế và hạnh phúc"
      description = "Lấy hạnh phúc con người làm trung tâm. Bắt đầu từ ước muốn làm nên sản phẩm tốt đẹp, người lao động mang yêu thương, bình an vào việc chế biến thủ công, tỉ mỉ. Khách hàng sẽ cảm nhận được năng lượng tích cực ấy khi sử dụng sản phẩm."
      # url = "#"

      [[params.services.row.list]]
        icon = "fa-gift"
        title = "Chia sẻ và nhân rộng"
        description = "Chia sẻ hiểu biết, kinh nghiệm và trở thành nơi trải nghiệm và học tập cho những bạn trẻ có đam mê và ý định khởi nghiệp trong lĩnh vực chế biến."
        # url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Sản phẩm"
    subtitle = "Chúng tôi đang cung cấp ..."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "Kể chuyện Ánh Phan Rang"
    subtitle = "Và lược sử hình thành xưởng chế biến nông sản Ông Thắng"
    endpoint = "Hãy tham gia cùng chúng tôi!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "1993"
      title = "Lên đường"
      description = "ông Thắng (ba Ánh) đưa cả nhà vào Phan Rang, khai hoang bãi nổi giữa cửa biển sông Dinh"

    [[params.about.events]]
      img = "2.jpg"
      date = "199x"
      title = "Tuổi thơ sinh động"
      description = "Ánh học cấp 2, giữa trưa mặc áo mưa chèo thuyền vịt đi học, thiếu điện, thiếu nước, làm bạn với nắng gió trời mây và chó."

    [[params.about.events]]
      img = "3.jpg"
      date = "2005-2009"
      title = "Ước muốn trồng rừng và học đại học"
      description = "Năm cấp 3, một ý nghĩ loé lên __mình sẽ đi trồng rừng!__ Ánh thi đậu đại học Nông Lâm Hồ Chí Minh. Vừa học vừa làm, phụ giúp kinh tế gia đình. Nhận được nhiều học bổng trợ giúp từ cộng đồng."

    [[params.about.events]]
      img = "4.jpg"
      date = "2009-2013"
      title = "Sự chuyên nghiệp và tử tế ở Pháp"
      description = "Ánh học thạc sĩ và làm ở Pháp về quản lý trong công nghiệp thực phẩm. Được sống giữa những người tử tế và tham gia các tổ chức phi chính phủ, đóng góp cho cộng đồng."

    [[params.about.events]]
      img = "5.jpg"
      date = "2013-2016"
      title = "Phát triển cộng đồng trong nước"
      description = "Ánh về nước dự định làm những gì mình muốn về phát triển cộng đồng. Gặp chị Hằng, làm cho XanhShop. Ánh góp phần xây dựng cộng đồng những người sống với nhau tử tế, thân thiết với nhà cung cấp như gia đình."

    [[params.about.events]]
      img = "6.jpg"
      date = "9/2016"
      title = "Trở về với gia đình, quê hương"
      description = "Ánh trở về Phan Rang gắn kết với gia đình, từng bước thực hiện ước muốn trồng rừng từ năm cấp 3. Bước đầu thử nghiệm làm vườn và chế biến nông sản địa phương"

    [[params.about.events]]
      img = "7.jpg"
      date = "5/2017"
      title = "Mở xưởng chế biến"
      description = "Ánh mở xưởng chế biến ông Thắng, sử dụng nông sản không hoá chất, đồng hành cùng những vườn canh tác thuận tự nhiên ở Ninh Thuận. Phát triển kỹ năng cho các bạn muốn triển khai mô hình tương tự tại địa phương mình sinh sống."

  # Team section
  [params.team]
    enable = false


  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      center = true
      # Optional client title specifying the involvement
      title = "Đối tác / bạn đồng hành tin cậy"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "xanh.jpg"
        link = "https://xanhshop.com/"

  # Contact section
  [params.contact]
    enable = true
    title = "Liên hệ"
    subtitle  = "__Địa chỉ__: khu phố 8, phường Phước Mỹ, TP Phan Rang – Tháp Chàm, tỉnh Ninh Thuận\n\n__Email__: [ongthangphanrang@gmail.com](mailto:ongthangphanrang@gmail.com)\n\n__Điện thoại__: [09 79 56 52 71](tel:+84979565271)"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Copyright 2018"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    # [[params.footer.quicklinks]]
    #   text = "Privacy Policy"
    #   link = "#"

    # [[params.footer.quicklinks]]
    #   text = "Terms of Use"
    #   link = "#"
